# Generated by Django 6.0.1 on 2026-02-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_alter_course_instructor_alter_lesson_video"),
        ("enrollments", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="lessonprogress",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "course"), name="unique_enrollment_per_student"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonprogress",
            constraint=models.UniqueConstraint(
                fields=("enrollment", "lesson"), name="unique_progress_per_lesson"
            ),
        ),
    ]
