# Generated by Django 6.0.1 on 2026-01-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="module",
            options={},
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("course", "order"), name="unique_module_order_per_course"
            ),
        ),
    ]
