# Generated by Django 6.0.1 on 2026-01-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_module_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["order"],
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
            },
        ),
        migrations.AlterModelOptions(
            name="module",
            options={
                "ordering": ["order"],
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
            },
        ),
    ]
