# Generated by Django 6.0.1 on 2026-02-06 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_lesson_options_alter_module_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Supported formats: .mp4, .webm, .ogg",
                null=True,
                upload_to="lessons/videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "webm", "ogg"]
                    )
                ],
            ),
        ),
    ]
