# Generated by Django 6.0.1 on 2026-02-11 07:00

import courses.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_add_video_to_lesson"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="profiles.instructor",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Supported formats: .mp4, .webm, .ogg (max 500MB)",
                null=True,
                upload_to="lessons/videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "webm", "ogg"]
                    ),
                    courses.validators.validate_video_file_size,
                ],
            ),
        ),
    ]
