# Generated by Django 6.0.1 on 2026-01-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SlugTestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=255, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Slug Test Model",
                "verbose_name_plural": "Slug Test Models",
            },
        ),
    ]
